name: Ubuntu 20.04 CI (GCC 9)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu-build:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use cmake (debug)
        run: |
          mkdir builddebug &&
          cd builddebug &&
          cmake -DCMAKE_BUILD_TYPE=buildundefsani ..  &&
          cmake --build .   &&
          ctest --output-on-failure
      - name: Use cmake (release)
        run: |
          mkdir buildrelease &&
          cd buildrelease &&
          cmake -DCMAKE_BUILD_TYPE=Release ..  &&
          cmake --build .   &&
          ctest --output-on-failure

      - name: Use cmake (undefined sanitizer)
        run: |
          mkdir buildundefsani &&
          cd buildundefsani &&
          cmake -DSTREAMVBYTE_SANITIZE_UNDEFINED=ON -DCMAKE_BUILD_TYPE=buildundefsani ..  &&
          cmake --build .   &&
          ctest --output-on-failure